### ISSUE TITLE
Some outline on title on navigation

### ISSUE THREAD

**Issue by mmrath** [mefechoel/svelte-navigator#10]
**Describe the bug**
On navigation title is highlighted. Looks worse than the attached screenshot when used with bootstrap. I could not figure out what is that outline.

<img width="437" alt="Screen Shot 2020-08-15 at 5 16 28 pm" src="https://user-images.githubusercontent.com/115767/90307641-8bc0c980-df1b-11ea-8e73-e387766096bd.png">

**To Reproduce**
1. Go to private-routes example and click on profile page

**Expected behavior**
The outline should not appear

**Screenshots**
attached, see the outline on "Login" title

**Comment by mefechoel** [comment]
The outline is a foucus indicator. It shows which element has focus, so keyboard users know where they are at in a page.
Focus indicators are critical for accessibility. If you're intersted you can read more about it [here](https://hacks.mozilla.org/2019/06/indicating-focus-to-improve-accessibility/).

Svelte Navigator tries to improve accessibility in SPAs by implementing a focus management system, which focuses a relevant heading on navigation. Again, if you're interested, [here](https://www.gatsbyjs.com/blog/2019-07-11-user-testing-accessible-client-routing/) is a great article, which describes how accessibility for SPAs can be improved. In fact, Svelte Navigators focus management is based upon suggestions from that study.

The dotted outline is just the browsers default style for the focus indicator. You can change it through CSS. There are some suggestions for that in the first article I've linked.

I might add some CSS to the examples in the future, to make it prettier and to give a suggestion on how to style it in an accessible way, but for now, I hope the explanation helps.

**Comment by mefechoel** [comment]
Closing because the observed behaviour is in fact the desired behaviour.

I've set up an issue to improve the documentation and examples, to better explain the behaviour and other accessibility related matters (see #11).

**Comment by mmrath** [comment]
@mefechoel accessibility is important but should this be a concern for router? Is it possible to provide some config to disable this feature or enable conditionally. I have not seen this feature in popular web apps.

**Comment by mefechoel** [comment]
@mmrath Actually I think it should be a routers concern, because SPA routers have, for the longest time broken accessibility (see [this article](https://medium.com/@robdel12/single-page-apps-routers-are-broken-255daa310cf)).

If you consider a non SPA, if you click a link, the browser loads a new html document and focus is reset to the body of the page.
A screen reader user is informed of the change and provided with some information on the rendered page.
If you use a SPA though, you never load a new document. So if you click a link, focus is set on the link. The page changes, but for a screen reader user it looks as tough nothing has happened. The focus is still on the link and no further information is announced.
This is, what Svelte Navigator fixes with its focus management.

Since the SPA router broke the accessibility, it should be its responsibility to fix it.
All major routers have issues regarding this (see [vue-router](https://github.com/vuejs/vue-router/issues/2488) and [react-router](https://github.com/ReactTraining/react-router/issues/5210)). Reach Router was, as far as I know, the first widely used router, [that implemented focus management](https://reach.tech/router/accessibility).
Svelte Navigators focus management works a little different from that of Reach Router.
I used suggestions from the article linked before and from [this tweet](https://twitter.com/ryanflorence/status/1130143041652531200) from Ryan Florence, one of the authors of Reach Router and React Router.

You can disable focus management, by passing `primary={false}` to your top level Router component, if you really want.
I would however advise not to do so, because you throw away a lot of accessibility you get for free, when using Svelte Navigator.
It all depends on your use case of course, but if you're planning on building an application you want other people to use, it's probably a good idea to leave it in and make it look nicer with CSS.

**Comment by lgk-bsw** [comment]
It's great that you take care for better accessibility. But I don't really understand why Svelte Navigator focuses only on the first heading element (`<h1>`-`<h6>`). Shouldn't it behave like the browser and just lose the focus on the link element? When you use a keyboard and press <kbd>Tab</kbd> the browser should automatically focus the first element on the new page.

**Comment by RaghavBhat02** [comment]
I agree. I appreciate the focus on accessibility, but it kinda looks horrendous when it focuses on the first heading element. My understanding is the SSR apps don't behave that way either. Would it not be better to simply change the focus back to the body instead (I may be wrong, but I believe this is what non-SPA apps do)?

**Comment by DatDraggy** [comment]
As the heading can't be focused by tabbing anyway I decided to just add `text-heading:focus { outline: none; }`. Shouldn't mess with accessibility too much, no?

**Comment by ollydixon** [comment]
How are we supposed to design our apps with this ugly blue outline everywhere? Kinda silly!

@DatDraggy thanks for the tip, it works but how can we apply this globally?

**Comment by mefechoel** [comment]
Yes, as mentioned before, you can safely disable focus rings on headings. See [comment with more detail on disabling focusrings](https://github.com/mefechoel/svelte-navigator/issues/54#issuecomment-1018611917).
But please **do not disable focus rings all together**. They are essential for keyboard navigation. But don't worry, you can style them like anything else ([see article about styling focusrings](https://css-tricks.com/having-a-little-fun-with-custom-focus-styles/)). The default focus indicator looks the way it does, because html and css is from the 90s and no default browser style looks good. You're styling your buttons, don't you, so why not also style focus indicators? You can find more [context and info in the readme](https://github.com/mefechoel/svelte-navigator#what-are-the-weird-rectangles-around-the-headings-in-my-app). I'll add some more explaimation about styling some time.
