### ISSUE TITLE
Login component not rendered when navigating directly to a PrivateRoute in provided example

### ISSUE THREAD

**Issue by mabentley85** [mefechoel/svelte-navigator#16]
**Describe the bug**
When pointing my browser to `http://localhost:6062/profile`, the URL is properly redirected to `http://localhost:6062/login` but the login form component is not displayed.

**To Reproduce**
1. Clone the repo
2. `cd svelte-navigator/example/private-routes`
3. Run `npm install` and `npm start`
4. Navigate to `http://localhost:6062/profile` in web browser
5. The URL is properly redirected to http://localhost:6062/login, but the login form component is not rendered as shown in the screen shot.  If you click the "Profile" link then the login form will be properly displayed.

**Expected behavior**
When you land on a private route the login form should be displayed.

**Screenshots**
![Screen Shot 2020-09-08 at 12 09 56 PM](https://user-images.githubusercontent.com/1074949/92517905-5894f180-f1cc-11ea-9a71-5d0c0b5c8075.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.8
 - Browsers: Chrome 85.0.4183.83, Firefox 80.0.1, Safari 13.1.2

**Comment by mefechoel** [comment]
This is probably what happened in #8. I can now reproduce the bug, thanks for the detailed description! I've had a look and I'm quite sure the bug originates in src/history.js, line 81.
It seems as though `history.replaceState` is asynchronous and does not immediately update `window.location`.

As I see it, there are three possible ways this could be fixed. Either wait a short time before updating the internal location. This is probably fragile and not a great idea. Maybe there is a browser event that is fired when the state is replaced, but I've not seen this in other history implementations, but it should be investigated.
Probably the best way to fix it now would be to manually parse the new path and create the next location from that.

**Comment by mefechoel** [comment]
Ok, I've identified the actual cause. `history.replaceState` is not asynchronous.
The problem was, that the navigation to `/login` occures before the `onMount` function of `Router` is called. The `Router` subscribes to changes in the history on mount. However the first change gets lost, because it occures before the `Router` has a chance to subscribe to the history.
To fix this, I had to change the behaviour of the history module. It now calles its subscribers (i.e. the `Router`) the moment they subscribe, and not only on changes, just like Svelte stores do.
