### ISSUE TITLE
Any way to disable the a11y?

### ISSUE THREAD

**Issue by stefan-holmgren** [mefechoel/svelte-navigator#18]
Is there any way to disable the a11y functionality?

I went from svelte-routing to this one, because it felt like it was much more mature - but for some reason a focus rectangle popped up.

It took me a while to figure out that it was the a11y that set the tab index for the element to -1.

I don't need/want to have a11y for the page I'm trying to build and just wonder if there's any way to disable the functionality?

**Comment by mefechoel** [comment]
Yes, you can disable the focus management by passing `primary={false}` to all top level `Router`s.

You should however consider styling the focus rings instead. Svelte Navigator gives you a lot of accessibility improvements for free, which you're not using when disabling focus management.
If the router didn't take focus, and you were to click a link, it would remain focused. Users relying on assistive technology like screenreaders would just not know that something changed on the page.
The idea of focusing a heading is, that it gives the user a starting point from where they can tab to the changed content.
Since it is just the starting point, you can disable the focus ring for just the headers, which aren't focusable by default anyway.
Or you could style them to better suit your design (see [this article about styling focus indicators](https://css-tricks.com/having-a-little-fun-with-custom-focus-styles/)).

**Comment by stefan-holmgren** [comment]
Thank you so much for the in-depth answer. I'll have to look into the accessibility way of thinking - currently I'm just looking into learning Svelte, and figuring out which routing library to use. Yours is very much up at the top of my list, so once again - thank you 💯
