### ISSUE TITLE
Variable assignment redeclares global property

### ISSUE THREAD

**Issue by hidde** [mefechoel/svelte-navigator#4]
In the [docs](https://github.com/mefechoel/svelte-navigator#uselocation), this line of code:

```js
const location = useLocation(); 
```

seems to redeclare the global `location` (`window.location`). Maybe this should use a different name that doesn't already exist in the browser?

**Comment by mefechoel** [comment]
It actually does not redeclare it, it shadows the global `location`. It might be an issue when using `var`, but Svelte probably wraps the component in a function anyways, so it would still just shadow `location`. 

This is just fine for js engines, and since you should not need to access `window.location`, when using a Router, shadowing it won't restrict you in development.

You're probably worried about it being confusing to users, rather than browser compatibility though, but I'd still argue, that when using a Router you should rely on it to be your source for location, rather than the browser.

It is also how [react-router](https://reacttraining.com/react-router/web/api/Hooks/uselocation) and [@reach/router](https://reach.tech/router/api/useLocation) do it.

I hope that clarifies it :)

**Comment by hidde** [comment]
Thanks for the explanation, that's very helpful! Was worried about user confusion _and_ compat, but seems neither are warranted here, thanks!
